### ISSUE TITLE
Review TeamCreation.jsx and TeamInvitationsWidget.jsx

### ISSUE THREAD

**Issue by winstonco** [hh-t1/hacc-hui-revamped#123]
# Files to Review

[TeamCreation.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/pages/participant/TeamCreation.jsx)
[TeamInvitationsWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/TeamInvitationsWidget.jsx#L29)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, October 9, 9:00 AM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by km584** [comment]
### **TeamCreation.jsx**

DE-03: L60, 76, 81, 124, 132, 136, 139, 144
JS-04: L51
JS-05: L151-153

### **TeamInvitationsWidget.jsx**

JS-05: L63, 75, 78, 90, 93, 105, 108, 120, 123, 151-154
RE-06: 180-194 define constants in withTracker()
RE-09
RE-10

**Comment by rhlai** [comment]
# TeamCreation.jsx

JS-04 & RE-09: L29
JS-05: L151,152,153
JS-06: L60, 76, 81, 124, 132, 136, 139, 144

#TeamInvitationsWidget.jsx

JS-04 & RE-09: L51
JS-05: L75, 90, 105, 120

**Comment by winstonco** [comment]
# outcome

## TeamCreation.jsx

- remove logs
- lodash
- bootstrap instead of semantic ui
- use function component
  - useRef
- use checkbox instead of radio
- use useTracker instead of withTracker
- add a test

## TeamInvitationsWidget.jsx

- remove unused variables
- lodash
- bootstrap
- function component
- useTracker
  - add collection subscriptions and return a field like "ready"
- test

- getSomething functions could use a filter instead of
```
const data = [];
...js
return data;
```

**Comment by Rubegen** [comment]
TeamCreation.jsx
DE-05: L60, L76, L108, L124, L139, L144
JS-04 L84 & L92
JS-05: L151-153

TeamInvitationsWidget.jsx
RE-09
JS-05: L75, L90, L105, L120
