### ISSUE TITLE
Review CreateProfileWidget.jsx and CreateTeamWidget.jsx

### ISSUE THREAD

**Issue by km584** [hh-t1/hacc-hui-revamped#126]
# Files to Review

[CreateProfileWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/CreateProfileWidget.jsx)
[CreateTeamWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/CreateTeamWidget.jsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, October 16, 9:00 AM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by winstonco** [comment]
CreateProfileWidget.jsx
the usual stuff:
- bootstrap
- function component
  - state
  - useTracker
- logs
- comments
- lodash

CreateTeamWidget.jsx
the usual stuff x2
- useRef in autoform

**Comment by rhlai** [comment]
# CreateProfileWidget.jsx

DE-05 & JS-06: L104
JS-04 & RE-09: L27
JS-05: L34-36
RE-10

# CreateTeamWidget.jsx

DE-05: L63, 90, 232
DE-05 & JS-06: L92, 110, 164
JS-05: L48-50, 140, 144
JS-06: 194
JS-04 & RE-09: L33
RE-10

**Comment by ntomchak** [comment]
CreateProfileWidget.jsx
DE-05: L70
JS-05: L34-36
JS-06: L104
RE-04, RE-09: Convert to function component with destructured props
RE-10: Remove widget from name


CreateTeamWidget.jsx
JS-05: L48-50, L140, L144
RE-04, RE-09
RE-10

**Comment by Rubegen** [comment]
CreateProfileWidget.jsx
RE-10
DE-05
JS-04
JS-05

CreateTeamWidget.jsx
RE-10
DE-05
JS-05
JS-06

**Comment by kaleinah** [comment]
CreateProfileWidget.js
RE-09: L27
JS-05: L14, 34-36
DE-04: L70, 104

CreateTeamWidget.js
RE-09: L33
JS-05: L12, 48-50, 140, 144
DE-04: L29-32, 63, 86-90, 110, 164, 182, 205, 232, 236

**Comment by km584** [comment]
### **CreateProfileWidgtet.jsx**
DE-03: L104
JS-05: L34-36
RE-09: L27

### **CreateTeamWidget.jsx**
DE-03: L63, 92, 110, 164, 232
JS-05: L48-50, 140, 144, 185
RE-06: L333
RE-09: L33

**Comment by kaleinah** [comment]
As a team we have concluded that these are the following changes that need to be implemented. 

CreateProfileWidget.js
RE-09: L27
RE-10: Remove widget from name
JS-05: L14, 34-36
DE-04: L70, 104

CreateTeamWidget.js
RE:06: L333
RE-09: L33
RE-10: Remove widget from name
JS-05: L12, 48-50, 140, 144, 185
DE-04: L29-32, 63, 86-90, 90, 92, 110, 164, 182, 205, 232, 236
