### ISSUE TITLE
Review MultiSelectField.tsx and RadioField.tsx

### ISSUE THREAD

**Issue by winstonco** [hh-t1/hacc-hui-revamped#129]
# Files to Review

[MultiSelectField.tsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/form-fields/MultiSelectField.tsx)
[RadioField.tsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/form-fields/RadioField.tsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, October 23, 9:00 AM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by winstonco** [comment]
MultiSelectField
- JS-06 remove logs
- JS-05 dont use lodash
- The formatting is bad
- Use bootstrap instead of semantic ui

RadioField.tsx
- JS-06 remove unnecessary logs, can keep the documentation, can remove the license from it
- Bad formatting
- Use bootstrap instead of semantic ui

**Comment by ntomchak** [comment]
MultiSelectField
JS-05
JS-06

RadioField
JS-06

**Comment by kaleinah** [comment]
MultiSelectField.tsx
JS-05: L5, 10-14
DE-03: L23
DE-05: L7, 9, 28
fix line space

RadioField.tsx
DE-04: L4-29
DE-05: L31, 32
fix line space

**Comment by rhlai** [comment]
# RadioField.tsx

DE-03: L31-32, 35. 

# MultiSelectField.tsx

DE-03: L7, 9, 28
JS-05: L10

**Comment by km584** [comment]
### **MultiSelectField.tsx**
DE-03: L9
JS-05: L10
Fix space at L52-57

### **RadioField.tsx**
DE-04: L4-L29
Fix space

**Comment by winstonco** [comment]
MultiSelectField.tsx
DE-03: L23
JS-05: L10
JS-06: L7, 9, 28
Bootstrap
Spacing

RadioField.tsx
JS-06: L31-32, 35
DE-05: L8-28
Bootstrap
Spacing
