### ISSUE TITLE
Review ManageHaccWidget.js & ManageMinorWidget.jsx

### ISSUE THREAD

**Issue by kaleinah** [hh-t1/hacc-hui-revamped#130]
# Files to Review

[ManageHaccWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/administrator/ManageHaccWidget.jsx)
[ManageMinorWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/administrator/ManageMinorWidget.jsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, October 30, 1:30 PM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by kaleinah** [comment]
ManageMinorWidget.jsx
DE-03: L9-12, 15, 60
Use function instead of class for React
Use tracker instead of with tracker 

ManageHaccWidget.jsx
DE-03: L16-20, 59, 158
Use function instead of class for React
Use tracker instead of with tracker

**Comment by winstonco** [comment]
ManageHaccWidget.jsx
- maybe remove eslint ignore on line 149
- useTracker

ManageMinorWidget.jsx
- remove or change documentation at the top
- useTracker

**Comment by ntomchak** [comment]
# ManageHaccWidget
remove lodash
switch to functional component with destructured props
useTracker


# ManageMinorWidget
useTracker

**Comment by km584** [comment]
### **ManageHaccWidget.js**
JS-05: L34, 47, 119, 152, 181
RE-06: L212

### **ManageMinorWidget.jsx**
JS-06: L82

**Comment by rhlai** [comment]
# ManageHaccWidget.jsx

DE-03: L211
RE-10

# ManageMinorWidget.jsx

DE-03: L73
RE-10

**Comment by rhlai** [comment]
## Results

# ManageHaccWidget.jsx

Remove lodash
Change WithTracker to UseTracker 
Remove Doc Comment
Remove Widget from name


# ManageMinorWidget.jsx

Remove or change doc comment
Change WithTracker to UseTracker
Remove Console.Log
Remove Widget from name
