### ISSUE TITLE
Review CreateProfileWidget.jsx & EditProfileWidget.jsx

### ISSUE THREAD

**Issue by kaleinah** [hh-t1/hacc-hui-revamped#143]
# Files to Review

[CreateProfileWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/CreateProfileWidget.jsx)
[EditProfileWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/EditProfileWidget.jsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, November 13th, 1:30 PM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by kaleinah** [comment]
**CreateProfileWidget.jsx**
- Use function instead of class
- Use useTracker() instead of withTracker()
- Maybe create local functions to replace mapping
JS-05: L16, 36-39
DE-03: L76, 110

**EditProfileWidget.jsx**
- Use function instead of class
- Use useTracker() instead of withTracker()
- Maybe create local functions to replace mapping
JS-05: L6, 44-46, 76, 80, 85, 
DE-03: L81, 93, 103, 137

- Would having "buildTheFormSchema()" as a component be better? it is used in both components

**Comment by Breadonn** [comment]
CreateProfileWidget.jsx:

L29 L35 L66=> JS-05 Convert to arrow function

L32 => Convert to useState

L110 => DE-03 Remove commented out code

EditProfileWIdget.jsx

L33 L43 L74 L92 => JS-05 Convert to arrow function

L36 => Convert to useState

L137 => DE-03 Remove commented out code

**Comment by Rubegen** [comment]
CreateProfileWidget.jsx
JS-05
RE-06
RE-09

EditProfileWidget.jsx
JS-04
JS-05
RE-09

**Comment by km584** [comment]
### **CreateProfileWidget.jsx**
DE-03: L76, 110
JS-05: L36-38, 69
RE-09
Convert to bootstrap

### **EditProfileWidget.jsx**
DE-03: L81, 93, 103, 137, 184
JS-05: L44-46, 76, 80, 85, 96, 252
RE-09
Convert to bootstrap

**Comment by rhlai** [comment]
# CreateProfile.jsx

Remove Console.logs
Avoid _ and lodash
Use usetracker instead of withTracker
Avoid use of widget in name

# EditProfileWidget.jsx\

Remove console.logs
Avoid _ and lodash
Use usetracker instead of withTracker
Avoid use of widget in name

**Comment by winstonco** [comment]
CreateProfileWidget.jsx
- semantic ui
- useTracker
- lodash
- function component
- useState
- bad name

EditProfileWidget.jsx
- useTracker
- semantic ui
- lodash
- function component
- useState
- useRef
- bad name
