### ISSUE TITLE
Review: HelpPage.jsx and Landing.jsx

### ISSUE THREAD

**Issue by Breadonn** [hh-t1/hacc-hui-revamped#37]
# Overview

The focus for this code review will be centered around HelpPage.jsx and Landing.jsx
Please pay attention to:

Javascript issues
React components

# Review Branch

review-001

# Files to Review

[HelpPage.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/pages/Landing.jsx)
[Landing.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/pages/HelpPage.jsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, September 11, 9:00 AM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by winstonco** [comment]
## Landing.jsx
### Architecture
- Looks good
### Design
- Page doc is meaningless
- `<br />` tags between 47-62 should be just multiple paragraphs
- Common styles should be pulled out, at least to a variable, maybe to a global file
### JavaScript and ESLint
- Looks good
### React
- Looks good
### Testing
- Exists, just checks if shows up

## HelpPage.jsx
### Architecture
- Looks good
### Design
- Looks good
### JavaScript and ESLint
- Should be an arrow fn
### React
- P and b tags combined are just headers
### Testing
- Exists, just checks if shows up

**Comment by rhlai** [comment]
# HelpPage.jsx
JS-04:L7 Use Arrow function instead
L23,43,46/49,59,67/70,75,93,106,122 does not require <b>

# Landing.jsx
DE-07: create style for column styling

**Comment by Breadonn** [comment]
## Landing.jsx:

L77, L93, L111, L127, L145, L160 => DE-07: Code should not be repeated more than twice (styles)

L47: change br tags

## HelpPage.jsx:

L21, L40, 57, L90 => DE-07: Code should not be repeated more than twice (paddingTop)

L7 => JS-04: Use arrow functions when appropriate (Can convert if we feel the need to)

L23, L42, L45, L58, L74, L92, L105, L121: bold in header

L30, L67, L83, L101, L109: just use header

**Comment by ntomchak** [comment]
HelpPage:
JS-04, component could use arrow function.

Landing:
DE-07, column styling

**Comment by Rubegen** [comment]
### Landing.jsx:

AR - OK

DE - repeated styling conventions throughout, 

JS - OK

### HelpPage.jsx:

AR - OK

DE - OK

JS - Use Arrow Function on comp

**Comment by km584** [comment]
### **Landing.jsx:**
L78, 94, 112, 128, 146, 161 => DE-07 use same style each column and using space more. Use style.css

### **HelpPage.jsx:**
L30, 66, 82, 100, 109: using <br> inside the <p> if using break in paragraph doesn't need <p>
L22, 25, 42, 45, 58, 74, 92, 105, 121: used <h> header and use <b> bold sentence. The header will bold and change size. No need <b>

**Comment by Breadonn** [comment]
# Outcome of review meeting

New Issues:
- Create an issue to make changes on landing.jsx
- Create an issue to make changes on HelpPage.jsx
