### ISSUE TITLE
Review: NavBar.jsx and SideBar.jsx

### ISSUE THREAD

**Issue by winstonco** [hh-t1/hacc-hui-revamped#40]
# Files to review
[NavBar.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/d97e5a128ac8a29d2d295b43304dad826eb68cb6/app/imports/ui/components/NavBar.jsx)
[SideBar.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/d97e5a128ac8a29d2d295b43304dad826eb68cb6/app/imports/ui/components/SideBar.jsx)

# Checklists
[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due date
September 17, 2023

**Comment by rhlai** [comment]
# Navbar.jsx
D-03: L8, 15, 23, 36, 37,, 123, 124
D-04: L109-113
D-07: remove instances of activeclassname at L46, 51, 57, 62, 68, 72, 77
RE-08: L177
RE-09: L21

# Sidebar.jsx
D-07: remove instances of activeclassname at L78, 84, 89, 94, 101, 105, 110, 119, 124, 131, 136, 141
JS-05: L44
RE-08: L186
RE-09: L21

**Comment by ntomchak** [comment]
NavBar.jsx
D-04: L8, L15, L23, L36-L37, L109-113, L123-124
RE-07: 
RE-09: L21

SideBar.jsx
DE-05: L173, L180, L185
JS-05: L8, L44
RE-09: L21

**Comment by rhlai** [comment]
# Navbar.jsx
DE-03: L8, 15, 23, 36,37, 123, 124
DE-04: L109-113
DE-07: remove activeClassName at L46, 51, 57, 62, 68, 72, 77, 86, 91, 96, 101, 105, 115, 119
RE-09: L21


# Sidebar.jsx
DE-07: remove activeClassName at 78, 84, 89, 94, 101, 105, 110, 119, 124, 131, 136, 141
JS-05: L44
RE-09: L21

**Comment by km584** [comment]
### **Navbar.jsx**
DE-04: L109-113
DE-05: L8, 15, 23, 36-37, 123-124
RE-09: L22

### **Sidebar.jsx**
JS-05: L8
RE-09: L21 Prefer to be function

**Comment by kaleinah** [comment]
**Navbar.jsx**
DE-03: L8, 15, 23, 36, 37, 123, 124
DE-04: L17-20, 108-113
RE-08: L171, 177
RE-09: L21

**Sidebar.jsx**
DE-03: L8
DE-04: L17-20
RE-09: L21
RE-08: L181, 186
JS-05: L44

**Comment by Breadonn** [comment]
NavBar.jsx

L8, L15, L23, L36, L37, L109-L113, L123, L124 => DE-04: Remove commented out code

L21 => Convert to function

L22 => Remove render once converted to a function

SideBar.jsx

L21 => Convert to function

L29 => Remove render once converted to function

**Comment by Rubegen** [comment]
### NavBar.jsx

DE-04 - L109-113
DE-04 L123-124
RE-09 L21

### SideBar.jsx

JS-05 L44
RE-09 L21

**Comment by winstonco** [comment]
## NavBar.jsx
### Architecture
Looks good
### Design
[DE-04][DE-05]: Could remove unnecessary comments
### JavaScript and ESLint
[JS-06]: Remove comments
### React
[RE-09]: Use a function component
[RE-06]: Define constants in withTracker (doesnt matter for us)
[RE-07]: Dont do data collection in render (also doesnt matter)
Using semantic ui
### Testing
[TA-01][TA-02]: No tests written

## SideBar.jsx
### Architecture
Looks good
### Design
[DE-07]: Styles could maybe be pulled out but honestly its fine
### JavaScript and ESLint
[JS-05]: Replace lodash functions with native array functions
### React
[RE-09]: Should be a function component
[RE-09]: State in useState
[RE-09]: useTracker instead of withTracker
Bootstrap instead of SemanticUI
### Testing
[TA-01][TA-02]: No tests written

**Comment by kaleinah** [comment]
**NavBar.jx**
DE-03: L8, 15, 23, 36, 37, 123, 124
DE-04: L17-20, 108-113
RE-08: L171, 177
RE-09: L21
- Menu.Item will be changed to use bootstrap
- Use tracker will be inside Navbar function export


**SideBar.jsx**
DE-03: L8
DE-04: L17-20
RE-09: L21, 181
RE-08: L181, 186
JS-05: L44
- Replace the visible state w/ use State hook (Starts line 24)
- Menu.Item will be changed to use bootstrap
- Use tracker will be inside Navbar function export
