### ISSUE TITLE
Review: SuggestToolSkillWidget.jsx and SuggestToolSkillWidgetAdmin.jsx

### ISSUE THREAD

**Issue by rhlai** [hh-t1/hacc-hui-revamped#77]
# Overview

The focus for this code review will be centered around SuggestToolSkillWidget.jsx and SuggestToolSkillWidgetAdmin.jsx
Please pay attention to:

Javascript issues
React components

# Review Branch

review-004

# Files to Review

[SuggestToolSkillWidgetAdmin.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/administrator/SuggestToolSkillWidgetAdmin.jsx)
[SuggestToolSkillWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/SuggestToolSkillWidget.jsx)

# Checklists

[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due Date

Monday, October 2, 9:00 AM

# For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f23/morea/review/reading-idpm-review.html

**Comment by Breadonn** [comment]
SuggestToolSkillWidgetAdmin.jsx

L19 => Convert to arrow function

L35, L43 => DE-04: Remove commented out code

L56 => Remove render once converted to function

SuggestToolSkillWidget.jsx

L20 => Convert to function

L36 => DE-04: Remove commented out code

L57 => Remove render once converted to function

**Comment by ntomchak** [comment]
SuggestToolSkillWidget.jsx
DE-05: L36, unnecessary comment
RE-09: L20, convert to function component
RE-10

SuggestToolSkillWidgetAdmin.jsx
DE-05: L35, L43, unnecessary comments
RE-09: L19, convert to function component
RE-10

**Comment by km584** [comment]
### **SuggestToolSkillWidgetAdmin.jsx**
DE-03: L35, 43
RE-07: L56

### **SuggestToolSkillWidget.jsx**
DE-03: L36
L64-86 Code line is not appropriate
RE-07: 57

**Comment by winstonco** [comment]
SuggestToolSkillWidget.jsx
Architecture
[AR-01]: Widget in the name
Design
[DE-05]: Random comments
JavaScript and ESLint
[ES-01]: Spacing is uneven
React
[RE-09]: Use a function component
[RE-09]: useState instead of this.state
[RE-09]: useTracker instead of withTracker
Use bootstrap instead of sem ui
Testing
[TA-01][TA-02]: No tests written, but tests are unnecessary

SuggestToolSkillWidgetAdmin.jsx
Exact same thing as above

**Comment by Rubegen** [comment]
SuggestToolSkillWidget.jsx

JS-04  - L19
DE-03 - L35
RE-10

SuggestToolSkillWidget.jsx
JS-04 
DE-03
RE-10

**Comment by ntomchak** [comment]
### SuggestToolSkillWidget.jsx
- make function component
- convert to bootstrap
- change name
- remove commented out console.log

### SuggestToolSkillWidgetAdmin.jsx
- make function component
- convert to bootstrap
- change name
- remove commented out console.log

**Comment by kaleinah** [comment]
SuggestToolSkillWidget.jsx
DE-03: L36
RE-09: L20


SuggestToolSkillWidgetAdmin.jsx
DE-03: L35, 43
RE-09: L19
